Name: Player8
Species: 7
Parts:
- Name: SK_ROBO_BASE_05_01HEAD_RO01
  PartType: Head
  PartVersion: 1
- Name: SK_SCFI_ROBO_03_10TORS_RO01
  PartType: Torso
  PartVersion: 1
- Name: SK_SCFI_ROBO_06_13ALWL_RO01
  PartType: ArmLowerLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_03_12AUPR_RO01
  PartType: ArmUpperRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_01_15HNDL_RO01
  PartType: HandLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_06_14ALWR_RO01
  PartType: ArmLowerRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_03_11AUPL_RO01
  PartType: ArmUpperLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_19LEGR_RO01
  PartType: LegRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_03_30ASHR_RO01
  PartType: AttachmentShoulderRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_20FOTL_RO01
  PartType: FootLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_03_17HIPS_RO01
  PartType: Hips
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_21FOTR_RO01
  PartType: FootRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_18LEGL_RO01
  PartType: LegLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_24ABAC_RO01
  PartType: AttachmentBack
  PartVersion: 1
- Name: SK_SCFI_ROBO_03_29ASHL_RO01
  PartType: AttachmentShoulderLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_01_16HNDR_RO01
  PartType: HandRight
  PartVersion: 1
ColorSet:
  Species: 7
  Name: Custom
  SourceColorPath: Assets\Level\Prefab\Player\Player7\Textures\T_Player7ColorMap.png
  SourceMetallicPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_MetallicMap.png
  SourceSmoothnessPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_SmoothnessMap.png
  SourceReflectionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ReflectionMap.png
  SourceEmissionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_EmissionMap.png
  SourceOpacityPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_OpacityMap.png
ColorRows:
- ColorProperty: 1
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 2
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 3
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 4
  MainColor: D09A78
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 5
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 6
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 7
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 8
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 9
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 10
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 11
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 12
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 13
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 14
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 15
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 16
  MainColor: FFF3CE
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 17
  MainColor: E5D8AF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 18
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 19
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 20
  MainColor: D0D0D0
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 21
  MainColor: D0D0D0
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 22
  MainColor: 6B4A27
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 23
  MainColor: 6B4A27
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 24
  MainColor: 262626
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 25
  MainColor: 262626
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 26
  MainColor: 8F6B46
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 27
  MainColor: 8F6B46
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 28
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 29
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 30
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 31
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 32
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 33
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 34
  MainColor: CAA58E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 35
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 36
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 37
  MainColor: CAA58E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 38
  MainColor: B35149
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 39
  MainColor: 944842
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 40
  MainColor: AFA382
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 41
  MainColor: 94896F
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 42
  MainColor: 2F323F
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 43
  MainColor: 8D483D
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 44
  MainColor: 5A677A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 45
  MainColor: B7AA9E
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 46
  MainColor: 2E2C29
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 47
  MainColor: 2F323F
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 48
  MainColor: 8D483D
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 49
  MainColor: 5A677A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 50
  MainColor: B7AA9E
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 51
  MainColor: 2E2C29
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 52
  MainColor: 2F323F
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 53
  MainColor: 8D483D
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 54
  MainColor: 5A677A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 55
  MainColor: B7AA9E
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 56
  MainColor: 2E2C29
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 57
  MainColor: 2F323F
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 58
  MainColor: 8D483D
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 59
  MainColor: 2E2C29
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 60
  MainColor: B7AA9E
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 61
  MainColor: 2E2C29
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 62
  MainColor: 2F323F
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 63
  MainColor: 8D483D
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 64
  MainColor: 2E2C29
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 65
  MainColor: B7AA9E
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 66
  MainColor: 2E2C29
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 67
  MainColor: 534045
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 68
  MainColor: 2F323F
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 69
  MainColor: 5A677A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 70
  MainColor: 8D5249
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 71
  MainColor: 9C744C
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 72
  MainColor: 625343
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 73
  MainColor: 3B3834
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 74
  MainColor: 625343
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 75
  MainColor: 907151
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 76
  MainColor: 784D49
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 77
  MainColor: 625343
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 78
  MainColor: 3B3834
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 79
  MainColor: 625343
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 80
  MainColor: 907151
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 81
  MainColor: 784D49
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 82
  MainColor: 625343
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 83
  MainColor: 3B3834
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 84
  MainColor: 625343
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 85
  MainColor: 907151
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 86
  MainColor: 784D49
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 87
  MainColor: 625343
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 88
  MainColor: 3B3834
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 89
  MainColor: 625343
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 90
  MainColor: 907151
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 91
  MainColor: 784D49
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 92
  MainColor: 625343
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 93
  MainColor: 985D41
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 94
  MainColor: B5B6B5
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 95
  MainColor: 536236
  Metallic: B5B6B5
  Smoothness: B5B6B5
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 96
  MainColor: 8D834E
  Metallic: B5B6B5
  Smoothness: B5B6B5
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 97
  MainColor: 486D92
  Metallic: B5B6B5
  Smoothness: B5B6B5
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 98
  MainColor: 383838
  Metallic: B5B6B5
  Smoothness: B5B6B5
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 99
  MainColor: 383838
  Metallic: B5B6B5
  Smoothness: B5B6B5
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 100
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 101
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 102
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 103
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 104
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 105
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 106
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 107
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 108
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 109
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 110
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 111
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 112
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 113
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 114
  MainColor: 383838
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 115
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 116
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 117
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 118
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 119
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 120
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 121
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 122
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 123
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 124
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 125
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 126
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 127
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 128
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 129
  MainColor: 383838
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 130
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 131
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 132
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 133
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 134
  MainColor: 383838
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 135
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 136
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 137
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 138
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 139
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 140
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 141
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 142
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 143
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 144
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 145
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 146
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 147
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 148
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 149
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 150
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 151
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 152
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 153
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 154
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 155
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 156
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 157
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 158
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 159
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 160
  MainColor: 7D736C
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 161
  MainColor: 6F685D
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 162
  MainColor: 5C564D
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 163
  MainColor: 49443F
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 164
  MainColor: C5A778
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 165
  MainColor: C99147
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 166
  MainColor: CD31A3
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 167
  MainColor: A32180
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 168
  MainColor: 90BAE4
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: 000000
- ColorProperty: 169
  MainColor: 88A6C4
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: 000000
- ColorProperty: 170
  MainColor: 9F2AF9
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 171
  MainColor: F92ACC
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 172
  MainColor: 9A9FA2
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 173
  MainColor: 949AA2
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 174
  MainColor: 8D997D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 175
  MainColor: 838865
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 176
  MainColor: 373532
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 177
  MainColor: 2B2926
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 178
  MainColor: 6D6964
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 179
  MainColor: 4A4C52
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 180
  MainColor: 807663
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 181
  MainColor: 6C624E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 182
  MainColor: 6C624E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 183
  MainColor: 5B4E3F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 184
  MainColor: 5E4A39
  Metallic: AAAAAA
  Smoothness: AAAAAA
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 185
  MainColor: 524132
  Metallic: AAAAAA
  Smoothness: AAAAAA
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 186
  MainColor: 604A34
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 187
  MainColor: 4B3C2F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 188
  MainColor: 8D7557
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 189
  MainColor: 5B4F3E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 190
  MainColor: 776B5B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 191
  MainColor: 63584A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 192
  MainColor: 97928D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 193
  MainColor: 86827E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 194
  MainColor: 70563F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 195
  MainColor: 83684F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 196
  MainColor: 3B8497
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 197
  MainColor: 3C626D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 198
  MainColor: 7B7879
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 199
  MainColor: 565656
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
BlendShapes:
  BodyTypeValue: 100
  BodySizeValue: -100
  MuscleValue: -100
